#MIGCLIM R script with post-defense feedback
library(MigClim)

#setwd("D:/OneDrive/PhD/CSF_ABM_Project/MigClim/MigClimRFiles/85_cc")

#order: ANHE, ANHE, ANHE, ANHE, ANHE, ANHE
#could do this as a for loop, but need models to pause so I can delete ASCII files

####################################################base model

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_base", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)

####################################################age

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=2, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_dage2", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=3, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_dage3", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=4, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_dage4", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=5, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=9,
                 simulName="ANHE_dage5", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=6, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_dage6", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)


####################################################rate

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.2),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_rate2", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.4),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_rate4", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.6),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_rate6", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.8),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_rate8", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(1),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_rate10", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)

####################################################distance

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.33,.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=6, lddMaxDist=4,
                 simulName="ANHE_distance2", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.45,.20,.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=9, lddMaxDist=4,
                 simulName="ANHE_distance3", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.684,.468,.320,.219,.150,.102),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_distance6", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(0.78, 0.61, 0.47, 0.37, 0.29, 0.22, 0.17, 0.14, 0.11),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_distance9", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(0.83, 0.68, 0.57, 0.47, 0.39, 0.32, 0.26, 0.22, 0.18, 0.15, 0.12, 0.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_distance12", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(0.90, 0.81, 0.73, 0.66, 0.59, 0.53, 0.48, 0.43, 0.39, 0.35, 0.32, 0.28, 0.26, 0.23, 0.21, 0.19, 0.17, 0.15, 0.14, 0.12, 0.11, 0.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_distance22", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)


####################################################ldd rate

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_lddrate05", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.10, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_lddrate10", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.15, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_lddrate15", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.20, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_lddrate20", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.25, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_lddrate25", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)

####################################################ldd dist

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=2, lddMaxDist=3,
                 simulName="ANHE_ldddist2", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_ldddist3", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_ldddist3", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=5, lddMaxDist=6,
                 simulName="ANHE_ldddist5", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.1),
                 iniMatAge=1, propaguleProd=c(1),
                 lddFreq=0.05, lddMinDist=10, lddMaxDist=11,
                 simulName="ANHE_ldddist10", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)

####################################################curve shape, higher = steeper

MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.23,.10,.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_shape5", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.27,.12,.1),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_shape6", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.32,.14,.1),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_shape7", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
MigClim.migrate (iniDist = "ANHE_Presence",
                 hsMap="ANHE_c45_",
                 rcThreshold = 200,
                 envChgSteps=4,
                 dispSteps=20,
                 dispKernel=c(.36,.16,.10),
                 iniMatAge=1, propaguleProd=c(1),
                 #lddFreq=0.05, lddMinDist=3, lddMaxDist=4,
                 simulName="ANHE_shape8", replicateNb=5, overWrite=TRUE,
                 testMode=FALSE, fullOutput=FALSE, keepTempFiles=TRUE)
